### ISSUE TITLE
Balancing

### ISSUE THREAD

**Issue by PeacefullyEpic** [dpinela/Transcendence#20]
Yeah, I wouldn't guess you're still active here, and this may just be me being pretentious, but I have some ideas for rebalancing some of the charms in mod.

First of all, overall, this is one of my favorite mods I've used. The charms feel super organic and fitting for the game, their effects are interesting and useful, and for the most part, they are balanced WAY better than other charm mods I've used *cough cough* fyrenest *cough cough*.

There are a few that are blatantly broken, though. I'll list my thoughts for them and one or two that might be better reworked.

Lemm's Strength
As it stands, this is probably the most broken charm in the game - more so than Always Furious Fury of the Fallen. If you plan on using this charm and don't sell anything to Lemm, you can get up to +39 damage - nearly tripling a Pure nail's damage - for the same cost as F/U Strength, which is +50% (which stacks on top of this, by the way, making it 90 total!). My rework would be simple - change the threshold for the damage increases. If you make it +1 damage every 3 relics for the first 15 (for a total of 5), then every 4 relics for the last 24 (for a total of 6), then it totals +11, equal to the max bonus from F/U Strength. Then it still incentivizes seeking out relics for a bit of extra damage but isn't completely game breaking once you have all of them.

Millibelle's Blessing
This charm is a gamebreak in and of itself - equip it and walk away for 24 hours and you can afford every buyable item in the game. There's a simple fix, though. It's already pretty good in normal gameplay, so just make it deactivate after 10 seconds of inactivity and boom, it's balanced.

Greedsong
This one isn't necessarily because it isn't balanced well, I just think it would make more sense for it to scale with the enemy that's hitting you. I would say something like every time you get hit you gain 25% or 50% of the geo worth of the enemy that dealt the damage, then have a set amount for any enemy that doesn't drop geo.

Marissa's Audience
This charm is strong but not overpowered when coupled with one familiar based charm at a time. As soon as you equip multiple, though, it's insane. Simple fix - the notch cost for Marissa's Audience is equal to the number of familiar based charms you have equipped (minimum 1). This way, you can still use it to double the effectiveness of familiar based gameplay, it's just now for the cost of more than a single charm notch.

Vespa's Vengeance
I don't actually have a rebalance for this, I just wanted to mention that I love this charm so dang much. As a proud Hive Knight skin user, it makes my heart happy.

**Comment by dpinela** [comment]
Thank you for the feedback - I am glad that you're enjoying the mod, and that you find the charms fit well in the game - that's just what I was going for with their design.

With regards to the changes you're suggesting:

- **Lemm's Strength**: of the charms you mention it's the strongest candidate for a potential nerf and really does get over the top if you max it out... but that's *if* you max it out. As you mention, you can always "nerf" the charm yourself by selling relics to Lemm, and you even get some extra geo for that, too. (Or if you're like me, you throw *all* your relics to Lemm and use the geo to fuel Shaman Amp instead. Did you know Amp also works on Vespa's Vengeance, by the way?) On the other hand, if I were to reduce its default damage value, you (and others) could not get the current max even if they wanted it. So I'd rather keep it as-is.
- **Millibelle's Blessing**: I considered this matter too while working on the mod, but ultimately, if someone wants to cheese their way to massive amounts of geo then they can already do that in seconds with the debug mod.
- **Greedsong**: I've considered making it scale with the *amount* of damage you take (so for example if you take double damage, you also get double the geo), which is in a similar spirit to what you suggested. But no promises.
- **Marissa's Audience**: In my opinion, even with all the familiars the charm isn't nearly as powerful as things like Lemm's Strength or Snail Soul. But also, making the notch cost variable is troublesome because it interacts with things like overcharm status, or potentially rando logic. Furthermore, if you're adding on more familiar charms, those already do cost extra notches (unless you got a very lucky rando seed), so that should cover it.
- **Vespa's Vengeance**: I'm slightly surprised you didn't suggest any balance changes to this - it can be *very* powerful in some situations! But I'm happy you like it; I had a blast creating it, too.

**Comment by PeacefullyEpic** [comment]
Thanks for the response! I wasn't expecting any response, so to get one so promptly and so respectfully feels pretty good.

As far as your responses to my suggestions, I was surprised, but after reading through them and thinking about them for a bit, I've actually come to agree with you on pretty much all of them. I realized that I was looking at the mod through the wrong perspective. I was looking at it as if I were the game developer, wanting things not to be exploitable or any of that. I should be, however, looking at it through the eyes of a modder/mod user. From that perspective, you've done even better with the mod than I originally thought. A mod user is already seeking out to change the game how they see fit, and therefore your clever integration of user choice with charms like Lemm's Strength and Shaman Amp as to how powerful they actually are is perfect for the target audience. Bravo.

In regards to Vespa's Vengeance in particular, I didn't include any balancing notes on it because I had not yet had the chance to use it. My notes in that regard are relatively simple. It would probably be less insane in its certain situations if the bees could only deal damage once, as with flukenest's projectiles. As is, since each can hit multiple times/multiple enemies, yeah, I can see how that could get crazy in the right circumstances. Other than that, maybe 10/20/15/30 instead of 15/30/20/40 would help to balance it, I dunno.

However, addressing the other reason I love that charm - it builds on Flukenest, a charm that seems oddly out of place in the base game. It's the only charm that changes a fundamental aspect of your dps kit unless you count sharp shadow, and it does it in a very interesting way. At the expense of some crowd control and a bit more difficulty in landing all the damage, it offers more single target damage overall. The two points I think you captured really well with Vengeance are the flavorful concept and the trading of a single large, extended active hitbox for many smaller, shorter hitboxes. You get both Flukenest and Vespa's Vengeance by defeating a boss (in my head cannon that VV and Hiveblood are switched in aquisition location) and then gaining a portion of that boss' power. I love that.

Now, the other thing I love is that it opens up a brainstorm for what could replace DD/DD. Here are my ideas.

Crystalline Crash
You perform a downward slam, similar to DD/DD, but do not gain I-frames. You also do not set off an explosive hitbox, instead creating a crystalline object akin to those created by the crystal shooter bugs from crystal peak which has a longer lasting but smaller hitbox and less damage. In place of the I-frames, you gain a crystal armor which prevents damage like Carefree Melody but disappears after 10 seconds or after tanking one hit.

Thorny Thlam (hehe, slam with a lisp)
You perform a downward slam, similar to DD/DD, but do not gain I-frames. You also do not set off an explosive hitbox, instead firing out 5/8 orange thorn projectiles akin to those fired by that one thorny bush husk enemy. These projectiles deal a small amount of damage in addition to having the unique effect of pinning a hit enemy in place for a number of seconds equal to twice the number of thorns that hit it.

Anyways, those are some more of my thoughts. Again, thanks so much for responding!

**Comment by dpinela** [comment]
It really would've been fitting for Vespa's to be found after Hive Knight, but alas, there is only one notable spot to put things there, and it was already taken up by Hiveblood. Rando can change that, of course, if you get lucky.

I like your thinking in extending the same concept to DD, and the two concepts you suggest are interesting. Bear in mind, though, that I am going for quality over quantity with this mod (partly out of space considerations; we can only add so many charms before the charm menu gets cramped and unwieldy), so the bar for any additional ones to be included in Transcendence is high, and rising with each new one added. In fact, I've had several ideas for charms since its initial release, and so far Vespa's Vengeance is the only one that proved compelling enough to get past that bar. Will there be more? Maybe, or maybe not. Can't really say for sure.

Likewise the boss concepts you mention may well make for some very cool modded bosses - in fact, I think you're not the first to think of a CG3 boss, and I find your "MMC with Thorns" idea to be quite amusing -, but such things are well outside the scope of what I want to do with Transcendence.

**Comment by PeacefullyEpic** [comment]
Fair enough, fair enough, and fair enough. I tried Fyrenest, which adds 30 charms, and it was just hard to look at.

And for the boss thing, yeah, I can see that being a much bigger task than would be reasonable - building a new arena, spriting, programming attack patterns, etc. To be honest, though, I've always been an avid daydreamer, so the inspiration for brainstorming and theorycrafting might actually be more important to me in the end than the actual execution of whatever I come up with. I actually fall into a similar boat with homebrew in D&D - I create a ton of my own content for the game but am more satisfied with the process of creation than I am with applying the homebrew when playing the game. Somehow keeping things as concepts rather than actually implementing them in game can, in some cases, make them more interesting for me. I know none of that means much to you, but in short, you creating Vespa's Vengeance opened me up to the idea of more spell changing charms, which will be fun for me to stew on for a while.

Wow, that was a lot of words to not say very much. Anyways, you're awesome.
