### ISSUE TITLE
the amulets do not appear

### ISSUE THREAD

**Issue by MiskoJoness** [dpinela/Transcendence#22]
Hello I have an Error and I dont know how solve, when I go into the game in the charms section, the 15 new notches that the mod includes appear, but when I go to the location where the charms should be to pick them up, they don't appear. I have all 3 mods needed to make it work. Sorry if something is not well written, I am Spanish

**Comment by dpinela** [comment]
I'm sorry I missed this for so long. If you used one of your existing save files, the issue is that Transcendence only places its charms when you create a new save file. You can still get the charms on an existing file by using the debug mod's "give all charms" button, or by editing the save file directly.

**Comment by FireBornFox** [comment]
same issue, new save, give all charms doesn't work also

**Comment by dpinela** [comment]
@FireBornFox can you provide a ModLog.txt from a session where you had this issue? (You can find that file in the same directory as your saves.)

**Comment by dpinela** [comment]
Closed due to inactivity.
