### ISSUE TITLE
Feature request: be more careful about removing default modules in other itemchanger modes

### ISSUE THREAD

**Issue by BadMagic100** [dpinela/Transcendence#4]
Removing default modules can cause issues in other itemchanger modes. For example, in Archipelago, if Transcendence is enabled accidentally, Elder Baldurs will not spit without VS and make greenpath unreachable even though it may be in logic via another baldur killer. There are various ways to do this, including but not limited to:

* Add a MenuChanger mode menu for transcendence.
  * Drawback: loses compatibility with other similar mods in the future
* Treat archipelago as an additional special case, that adds the items at their vanilla locations but doesn't do other things
  * Drawback: requires keeping a list of all the edge cases which may not scale in the future
* Make the mod globally togglable (see #3)
  * Drawback: this is probably clunky (as mentioned on #3)

**Comment by dpinela** [comment]
A specific mode menu for Transcendence doesn't make sense, since the mod is meant to work with all the standard game modes as well as randomizer. Making the mod togglable isn't doable right now as I explained in #3. Not removing the modules makes the vanilla experience, well, not so vanilla. So I think the best solution for the time being is in fact to add a special case to not disable the modules for Archipelago.

If ItemChanger didn't enable any modules by default we'd also have no problems, since Transcendence doesn't want to add any itself.

**Comment by dpinela** [comment]
Turns out ItemChanger actually had a solution for this all along - when creating a settings profile I can make it not create the default modules *if* another mod hasn't created the profile already. That way if some other mod's using ItemChanger (like rando or Archipelago) we don't mess with modules at all.

**Comment by BadMagic100** [comment]
[this signature](https://homothetyhk.github.io/HollowKnight.ItemChanger/api/ItemChanger.ItemChangerMod.html#ItemChanger_ItemChangerMod_CreateSettingsProfile_System_Boolean_System_Boolean_) for CreateSettingsProfile may be of interest. You'd need to make sure you do this after everything else though, as it seems only the first requester gets priority for default modules

**Comment by dpinela** [comment]
That's exactly what I was talking about. It works out fine for rando at least, because at the point where I call CreateSettingsProfile has created its own already. I don't know about Archipelago; I can't find source code for the mod anywhere.

**Comment by BadMagic100** [comment]
Ah, you found it while I was typing a comment. Here's AP source, I assume it's probably similar to how rando does it as I believe it's used much of the code as reference but haven't verified 

https://github.com/Ijwu/Archipelago.HollowKnight

**Comment by dpinela** [comment]
I had a look and yep, it too, like rando, sets up ItemChanger's settings before calling UIManager.StartNewGame. So our trick works fine for both.

**Comment by dpinela** [comment]
This is (or at least should be) resolved in 1.1.
